sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.17.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - make up
  - make test

after_success:
  - docker build -t rkeplin/bible-php-api:$TRAVIS_BUILD_NUMBER .
  - docker build -t rkeplin/bible-php-api:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rkeplin/bible-php-api:$TRAVIS_BUILD_NUMBER
  - docker push rkeplin/bible-php-api:latest
  - bash <(curl -s https://codecov.io/bash)
  - git checkout -- .

deploy:
  provider: script
  script: bash $(pwd)/.deploy/deploy.sh
  on:
    branch: master
