name: Unit Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and start services
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: sleep 15

      - name: Run unit tests
        run: docker compose exec -T -e XDEBUG_MODE=off php-api sh -c "cd tests && /usr/local/bin/phpunit --testsuite 'Unit Tests'"
